const verses = [
    "It is better to live your own destiny imperfectly than to live an imitation of somebody else's life with perfection.",
    "You have the right to work, but never to the fruit of work.",
    "Change is the law of the universe. You can be a millionaire or a pauper in an instant.",
    "Man is made by his belief. As he believes, so he is.",
    "Whatever happened, happened for the good. Whatever is happening, is happening for the good. Whatever will happen, will also happen for the good.",
    "Perform your obligatory duty, because action is indeed better than inaction.",
    "The soul is neither born, nor does it die.",
    "You have a right to perform your prescribed duties, but you are not entitled to the fruits of your actions.",
    "The mind acts like an enemy for those who do not control it.",
    "Through selfless service, you will always be fruitful and find the fulfillment of your desires.",
    "Just as a candle cannot burn without fire, men cannot live without a spiritual life.",
    "There is nothing lost or wasted in this life.",
    "As the heat of a fire reduces wood to ashes, the fire of knowledge burns to ashes all karma.",
    "Lust, anger and greed are the three gates to self-destructive hell.",
    "We are kept from our goal not by obstacles but by a clear path to a lesser goal.",
    "Peace comes from within. Do not seek it without.",
    "For one who has conquered his mind, a mind is best of friends, but for one who has failed to do so, a mind is the greatest enemy.",
    "One who sees inaction in action, and action in inaction, is intelligent among men.",
    "No one who does good work will ever come to a bad end, either here or in the world to come.",
    "When meditation is mastered, the mind is unwavering like the flame of a lamp in a windless place.",
    "Knowledge is better than mechanical practice. Meditation is better than knowledge. Renunciation of the fruits of action is better than meditation.",
    "The self-controlled soul, who moves amongst sense objects, free from either attachment or repulsion, achieves peace.",
    "The happiness which comes from long practice, which leads to the end of suffering, which at first is like poison, but at last like nectar - this kind of happiness arises from the serenity of one's own mind.",
    "Perform work in this world, Arjuna, as a man established within himself – without selfish attachments, and alike in success and defeat.",
    "Better than mechanical practice is knowledge. Better than knowledge is meditation.",
    "The power of God is with you at all times; through the activities of mind, senses, breathing, and emotions; and is constantly doing all the work using you as a mere instrument.",
    "The soul can never be cut to pieces by any weapon, nor burned by fire, nor moistened by water, nor withered by the wind.",
    "He who has let go of hatred who treats all beings with kindness and compassion, who is always serene, unmoved by pain or pleasure, free of the 'I' and 'mine,' self-controlled, firm and patient.",
    "There is neither this world, nor the world beyond, nor happiness for the one who doubts.",
    "A gift is pure when it is given from the heart to the right person at the right time and at the right place, and when we expect nothing in return.",
    "Pleasures conceived in the world of the senses have a beginning and an end and give birth to misery.",
    "The wise work for the welfare of the world, without thought for themselves.",
    "Even the wise are confused about what is action and what is inaction.",
    "The supreme reality stands revealed in the consciousness of those who have conquered themselves.",
    "They live in wisdom who see themselves in all and all in them.",
    "The mind is restless and difficult to restrain, but it is subdued by practice.",
    "Better indeed is knowledge than mechanical practice. Better than knowledge is meditation.",
    "The one who has faith, who is absorbed in the Supreme and who has subdued the senses gains knowledge.",
    "The soul who meditates on the Self is content to serve the Self and rests satisfied within the Self.",
    "Actions do not cling to me because I am not attached to their results.",
    "He who sees Me everywhere and sees everything in Me, I am not lost to him, nor is he lost to Me.",
    "The one who is motivated only by the desire for the fruits of their action, and anxious about the results, is miserable indeed.",
    "When a person responds to the joys and sorrows of others as if they were his own, he has attained the highest state of spiritual union.",
    "Those who are motivated only by desire for the fruits of action are miserable, for they are constantly anxious about the results of what they do.",
    "The wise see that there is action in the midst of inaction and inaction in the midst of action.",
    "The embodied soul is eternal in existence, indestructible, and infinite.",
    "As a person puts on new garments, giving up old ones, similarly, the soul accepts new material bodies, giving up the old and useless ones.",
    "There has never been a time when you and I have not existed, nor will there be a time when we will cease to exist.",
    "The wise grieve neither for the living nor for the dead.",
    "Reshape yourself through the power of your will; never let yourself be degraded by self-will.",
    "The soul who meditates on the Self is content to serve the Self and rests satisfied within the Self.",
    "As the blazing fire reduces wood to ashes, similarly, the fire of Self-knowledge reduces all Karma to ashes.",
    "The one who sees inaction in action and action in inaction has understanding among men.",
    "The self-controlled person, moving among objects, with his senses free from attachment and malevolence and brought under his own control, attains tranquility.",
    "The happiness which comes from long practice, which leads to the end of suffering, which at first is like poison, but at last like nectar - this kind of happiness arises from the serenity of one's own mind.",
    "The power of God is with you at all times; through the activities of mind, senses, breathing, and emotions; and is constantly doing all the work using you as a mere instrument.",
    "The soul can never be cut to pieces by any weapon, nor burned by fire, nor moistened by water, nor withered by the wind.",
    "He who has let go of hatred who treats all beings with kindness and compassion, who is always serene, unmoved by pain or pleasure, free of the 'I' and 'mine,' self-controlled, firm and patient.",
    "There is neither this world, nor the world beyond, nor happiness for the one who doubts.",
    "A gift is pure when it is given from the heart to the right person at the right time and at the right place, and when we expect nothing in return.",
    "Pleasures conceived in the world of the senses have a beginning and an end and give birth to misery.",
    "The wise work for the welfare of the world, without thought for themselves.",
    "Even the wise are confused about what is action and what is inaction.",
    "The supreme reality stands revealed in the consciousness of those who have conquered themselves.",
    "They live in wisdom who see themselves in all and all in them.",
    "The mind is restless and difficult to restrain, but it is subdued by practice.",
    "Better indeed is knowledge than mechanical practice. Better than knowledge is meditation.",
    "The one who has faith, who is absorbed in the Supreme and who has subdued the senses gains knowledge.",
    "The soul who meditates on the Self is content to serve the Self and rests satisfied within the Self.",
    "Actions do not cling to me because I am not attached to their results.",
    "He who sees Me everywhere and sees everything in Me, I am not lost to him, nor is he lost to Me.",
    "The one who is motivated only by the desire for the fruits of their action, and anxious about the results, is miserable indeed.",
    "When a person responds to the joys and sorrows of others as if they were his own, he has attained the highest state of spiritual union.",
    "Those who are motivated only by desire for the fruits of action are miserable, for they are constantly anxious about the results of what they do.",
    "The wise see that there is action in the midst of inaction and inaction in the midst of action.",
    "The embodied soul is eternal in existence, indestructible, and infinite.",
    "As a person puts on new garments, giving up old ones, similarly, the soul accepts new material bodies, giving up the old and useless ones.",
    "There has never been a time when you and I have not existed, nor will there be a time when we will cease to exist.",
    "The wise grieve neither for the living nor for the dead.",
    "Reshape yourself through the power of your will; never let yourself be degraded by self-will.",
    "The soul who meditates on the Self is content to serve the Self and rests satisfied within the Self.",
    "As the blazing fire reduces wood to ashes, similarly, the fire of Self-knowledge reduces all Karma to ashes.",
    "The one who sees inaction in action and action in inaction has understanding among men.",
    "The self-controlled person, moving among objects, with his senses free from attachment and malevolence and brought under his own control, attains tranquility.",
    "The happiness which comes from long practice, which leads to the end of suffering, which at first is like poison, but at last like nectar - this kind of happiness arises from the serenity of one's own mind.",
    "The power of God is with you at all times; through the activities of mind, senses, breathing, and emotions; and is constantly doing all the work using you as a mere instrument.",
    "The soul can never be cut to pieces by any weapon, nor burned by fire, nor moistened by water, nor withered by the wind.",
    "He who has let go of hatred who treats all beings with kindness and compassion, who is always serene, unmoved by pain or pleasure, free of the 'I' and 'mine,' self-controlled, firm and patient.",
    "There is neither this world, nor the world beyond, nor happiness for the one who doubts.",
    "A gift is pure when it is given from the heart to the right person at the right time and at the right place, and when we expect nothing in return.",
    "Pleasures conceived in the world of the senses have a beginning and an end and give birth to misery.",
    "The wise work for the welfare of the world, without thought for themselves.",
    "Even the wise are confused about what is action and what is inaction.",
    "The supreme reality stands revealed in the consciousness of those who have conquered themselves.",
    "They live in wisdom who see themselves in all and all in them.",
    "The mind is restless and difficult to restrain, but it is subdued by practice.",
    "Better indeed is knowledge than mechanical practice. Better than knowledge is meditation.",
    "The one who has faith, who is absorbed in the Supreme and who has subdued the senses gains knowledge.",
    "The soul who meditates on the Self is content to serve the Self and rests satisfied within the Self.",
    "Actions do not cling to me because I am not attached to their results.",
    "He who sees Me everywhere and sees everything in Me, I am not lost to him, nor is he lost to Me.",
    "The one who is motivated only by the desire for the fruits of their action, and anxious about the results, is miserable indeed.",
    "When a person responds to the joys and sorrows of others as if they were his own, he has attained the highest state of spiritual union.",
    "Those who are motivated only by desire for the fruits of action are miserable, for they are constantly anxious about the results of what they do.",
    "The wise see that there is action in the midst of inaction and inaction in the midst of action.",
    "The embodied soul is eternal in existence, indestructible, and infinite.",
    "As a person puts on new garments, giving up old ones, similarly, the soul accepts new material bodies, giving up the old and useless ones.",
    "There has never been a time when you and I have not existed, nor will there be a time when we will cease to exist.",
    "The wise grieve neither for the living nor for the dead.",
    "Reshape yourself through the power of your will; never let yourself be degraded by self-will.",
    "The soul who meditates on the Self is content to serve the Self and rests satisfied within the Self.",
    "As the blazing fire reduces wood to ashes, similarly, the fire of Self-knowledge reduces all Karma to ashes.",
    "The one who sees inaction in action and action in inaction has understanding among men.",
    "The self-controlled person, moving among objects, with his senses free from attachment and malevolence and brought under his own control, attains tranquility."
];

document.getElementById('newVerse').addEventListener('click', () => {
    const randomIndex = Math.floor(Math.random() * verses.length);
    document.getElementById('verse').textContent = verses[randomIndex];
});